# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from pyqtgraph import PlotWidget

class Ui_Manual_Baseline_Correction(object):
    def setupUi(self, Manual_Baseline_Correction):
        Manual_Baseline_Correction.setObjectName("Manual_Baseline_Correction")
        Manual_Baseline_Correction.resize(1145, 720)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Manual_Baseline_Correction)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = PlotWidget(Manual_Baseline_Correction)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Manual_Baseline_Correction)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(Manual_Baseline_Correction)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(Manual_Baseline_Correction)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Manual_Baseline_Correction)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(Manual_Baseline_Correction)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 1, 2, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(Manual_Baseline_Correction)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout.addWidget(self.horizontalSlider_3, 2, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.pushButton = QtWidgets.QPushButton(Manual_Baseline_Correction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Manual_Baseline_Correction)
        QtCore.QMetaObject.connectSlotsByName(Manual_Baseline_Correction)

    def retranslateUi(self, Manual_Baseline_Correction):
        _translate = QtCore.QCoreApplication.translate
        Manual_Baseline_Correction.setWindowTitle(_translate("Manual_Baseline_Correction", "Manual_Baseline_Correction"))
        self.label.setText(_translate("Manual_Baseline_Correction", "Iteration"))
        self.label_2.setText(_translate("Manual_Baseline_Correction", "Difference"))
        self.label_3.setText(_translate("Manual_Baseline_Correction", "Smoothing"))
        self.pushButton.setText(_translate("Manual_Baseline_Correction", "Baseline Correct"))
