# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from pyqtgraph import PlotWidget

class Ui_Manual_Baseline_Correction(object):
    def setupUi(self, Manual_Baseline_Correction):
        Manual_Baseline_Correction.setObjectName("Manual_Baseline_Correction")
        Manual_Baseline_Correction.resize(870, 720)
        self.graphicsView = PlotWidget(Manual_Baseline_Correction)
        self.graphicsView.setGeometry(QtCore.QRect(30, 20, 811, 551))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalSlider = QtWidgets.QSlider(Manual_Baseline_Correction)
        self.horizontalSlider.setGeometry(QtCore.QRect(130, 590, 451, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(Manual_Baseline_Correction)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(130, 620, 451, 31))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(Manual_Baseline_Correction)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(130, 650, 451, 31))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label = QtWidgets.QLabel(Manual_Baseline_Correction)
        self.label.setGeometry(QtCore.QRect(20, 590, 67, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Manual_Baseline_Correction)
        self.label_2.setGeometry(QtCore.QRect(20, 620, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Manual_Baseline_Correction)
        self.label_3.setGeometry(QtCore.QRect(20, 650, 81, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Manual_Baseline_Correction)
        self.pushButton.setGeometry(QtCore.QRect(630, 600, 191, 61))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Manual_Baseline_Correction)
        QtCore.QMetaObject.connectSlotsByName(Manual_Baseline_Correction)

    def retranslateUi(self, Manual_Baseline_Correction):
        _translate = QtCore.QCoreApplication.translate
        Manual_Baseline_Correction.setWindowTitle(_translate("Manual_Baseline_Correction", "Manual_Baseline_Correction"))
        self.label.setText(_translate("Manual_Baseline_Correction", "Iteration"))
        self.label_2.setText(_translate("Manual_Baseline_Correction", "Difference"))
        self.label_3.setText(_translate("Manual_Baseline_Correction", "Smoothing"))
        self.pushButton.setText(_translate("Manual_Baseline_Correction", "Baseline Correct"))
