# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import GraphicsLayoutWidget

class Ui_Manual_Recalibration(object):
    def setupUi(self, Manual_Recalibration):
        Manual_Recalibration.setObjectName("Manual_Recalibration")
        Manual_Recalibration.resize(1145, 720)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Manual_Recalibration)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Manual_Recalibration)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.graphicsView = GraphicsLayoutWidget(Manual_Recalibration)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(Manual_Recalibration)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Manual_Recalibration)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Manual_Recalibration)
        QtCore.QMetaObject.connectSlotsByName(Manual_Recalibration)

    def retranslateUi(self, Manual_Recalibration):
        _translate = QtCore.QCoreApplication.translate
        Manual_Recalibration.setWindowTitle(_translate("Manual_Recalibration", "Form"))
        self.pushButton.setText(_translate("Manual_Recalibration", "Re-calibrate"))
        self.pushButton_2.setText(_translate("Manual_Recalibration", "Clear"))
