# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import GraphicsLayoutWidget

class Ui_Manual_Recalibration(object):
    def setupUi(self, Manual_Recalibration):
        Manual_Recalibration.setObjectName("Manual_Recalibration")
        Manual_Recalibration.resize(1145, 720)
        self.graphicsView = GraphicsLayoutWidget(Manual_Recalibration)
        self.graphicsView.setGeometry(QtCore.QRect(330, 20, 801, 611))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(Manual_Recalibration)
        self.pushButton.setGeometry(QtCore.QRect(640, 650, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Manual_Recalibration)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 311, 611))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_2 = QtWidgets.QPushButton(Manual_Recalibration)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 650, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Manual_Recalibration)
        QtCore.QMetaObject.connectSlotsByName(Manual_Recalibration)

    def retranslateUi(self, Manual_Recalibration):
        _translate = QtCore.QCoreApplication.translate
        Manual_Recalibration.setWindowTitle(_translate("Manual_Recalibration", "Form"))
        self.pushButton.setText(_translate("Manual_Recalibration", "Re-calibrate"))
        self.pushButton_2.setText(_translate("Manual_Recalibration", "Clear"))
