# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plot(object):
    def setupUi(self, Plot):
        Plot.setObjectName("Plot")
        Plot.resize(1120, 720)
        self.graphicsView = GraphicsLayoutWidget(Plot, show=True)
        self.graphicsView.setGeometry(QtCore.QRect(20, 40, 511, 301))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = GraphicsLayoutWidget(Plot, show=True)
        self.graphicsView_2.setGeometry(QtCore.QRect(580, 40, 511, 301))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = GraphicsLayoutWidget(Plot, show=True)
        self.graphicsView_3.setGeometry(QtCore.QRect(310, 400, 511, 301))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label = QtWidgets.QLabel(Plot)
        self.label.setGeometry(QtCore.QRect(520, 370, 91, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Plot)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Plot)
        self.label_3.setGeometry(QtCore.QRect(720, 20, 241, 17))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Plot)
        QtCore.QMetaObject.connectSlotsByName(Plot)

    def retranslateUi(self, Plot):
        _translate = QtCore.QCoreApplication.translate
        Plot.setWindowTitle(_translate("Plot", "Form"))
        self.label.setText(_translate("Plot", "Comparison"))
        self.label_2.setText(_translate("Plot", "Original"))
        self.label_3.setText(_translate("Plot", "Baseline Corrected & Re-calibrated"))
from pyqtgraph import GraphicsLayoutWidget